"""Add telegram fields to creatives

Revision ID: 001_telegram_fields
Revises: 
Create Date: 2024-08-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_telegram_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - updated for Telegram storage ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('google_access_token', sa.String(), nullable=True),
    sa.Column('google_refresh_token', sa.String(), nullable=True),
    sa.Column('google_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('geo_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_seq', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo', 'date')
    )
    op.create_table('creatives',
    sa.Column('creative_id', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('drive_file_id', sa.String(), nullable=True),
    sa.Column('drive_link', sa.String(), nullable=True),
    sa.Column('uploader_user_id', sa.Integer(), nullable=False),
    sa.Column('uploader_buyer_id', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('upload_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('creative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - updated for removal ###
    op.drop_table('creatives')
    op.drop_table('geo_counters')
    op.drop_table('users')
    # ### end Alembic commands ###